DROP TABLE ACCESS_POINTS;
DROP TABLE ACCESS_LISTS;
CREATE TABLE ACCESS_POINTS (
	APID    SERIAL,
	APNAME  VARCHAR(100) UNIQUE,
	APIP	VARCHAR(15)
	
);

CREATE TABLE ACCESS_LISTS (
	ALID	 SERIAL,
	MACADDR	 VARCHAR(20) UNIQUE,
	HOSTIP	 VARCHAR(15),
	APID	 INT NOT NULL,
	STAN	 INT DEFAULT '0',
	PRIMARY KEY(HOSTIP, APID)
);

INSERT INTO ACCESS_POINTS (APNAME,APIP) VALUES('PawqLinksysRouter','192.168.1.1');
INSERT INTO ACCESS_LISTS  (MACADDR, HOSTIP, APID) VALUES('00:01:02:03:04:05','192.168.1.100',(select APID from ACCESS_POINTS where APNAME='PawqLinksysRouter'));
INSERT INTO ACCESS_LISTS  (MACADDR, HOSTIP, APID) VALUES('05:04:03:02:01:00','192.168.1.101',(select APID from ACCESS_POINTS where APNAME='PawqLinksysRouter'));
INSERT INTO ACCESS_LISTS  (MACADDR, HOSTIP, APID) VALUES('00:ff:aa:ee:ff:aa','192.168.1.102',(select APID from ACCESS_POINTS where APNAME='PawqLinksysRouter'));
INSERT INTO ACCESS_LISTS  (MACADDR, HOSTIP, APID) VALUES('00:01:02:03:04:05','192.168.1.103',(select APID from ACCESS_POINTS where APNAME='PawqLinksysRouter'));
