#!/bin/sh
if [ ! $upbw ]; then
         upbw=120;
fi
if [ ! $qosif ]; then
         qosif=eth0
fi

#  Priorytety: 10,11,12,13,15,16(ten moze zajac max polowe uploadu - domyslny)

# 10 - Najwyzszy - static = icmps,syn,acks
PRIO_HIGH_10="8074 9000"
# 11 static are = 53
PRIO_11="22 23 2222 80 443 17282"
PRIO_12="25 110 3306 8080 8000 17282"
PRIO_13="8081 21 20"
PRIO_15="1024:"



# changes mtu on the outbound device.  Lowering the mtu will result
# in lower latency but will also cause slightly lower throughput due
# to IP and TCP protocol overhead.
#ip link set dev $DEV mtu 1000


DEV=$qosif
RATEUP=$upbw
echo "[!] Instalujemy sie na $DEV z RATEUP $RATEUP"

# set queue size to give latency of about 2 seconds on low-prio packets
ip link set dev $DEV qlen 30

#Reset
tc qdisc del dev $DEV root    2> /dev/null > /dev/null
iptables -t mangle -D POSTROUTING -o $DEV -j MYSHAPER-OUT 2> /dev/null > /dev/null
iptables -t mangle -F MYSHAPER-OUT 2> /dev/null > /dev/null
iptables -t mangle -X MYSHAPER-OUT 2> /dev/null > /dev/null

tc qdisc add dev $DEV root handle 1: htb default 16 r2q 2
tc class add dev $DEV parent 1: classid 1:1 htb rate ${RATEUP}kbit

tc class add dev $DEV parent 1:1 classid 1:10 htb rate `expr $RATEUP / 6`kbit ceil ${RATEUP}kbit prio 0
tc class add dev $DEV parent 1:1 classid 1:11 htb rate `expr $RATEUP / 6`kbit ceil ${RATEUP}kbit prio 1
tc class add dev $DEV parent 1:1 classid 1:12 htb rate `expr $RATEUP / 6`kbit ceil ${RATEUP}kbit prio 2
tc class add dev $DEV parent 1:1 classid 1:13 htb rate `expr $RATEUP / 6`kbit ceil ${RATEUP}kbit prio 3
tc class add dev $DEV parent 1:1 classid 1:15 htb rate `expr $RATEUP / 6`kbit ceil ${RATEUP}kbit prio 5
tc class add dev $DEV parent 1:1 classid 1:16 htb rate `expr $RATEUP / 6`kbit ceil `expr $RATEUP / 2`kbit prio 6

tc qdisc add dev $DEV parent 1:10 handle 10: sfq perturb 10
tc qdisc add dev $DEV parent 1:11 handle 11: sfq perturb 10
tc qdisc add dev $DEV parent 1:12 handle 12: sfq perturb 10
tc qdisc add dev $DEV parent 1:13 handle 13: sfq perturb 10
tc qdisc add dev $DEV parent 1:15 handle 15: sfq perturb 10
tc qdisc add dev $DEV parent 1:16 handle 16: sfq perturb 10

tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 10 fw flowid 1:10
tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 11 fw flowid 1:11
tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 12 fw flowid 1:12
tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 13 fw flowid 1:13
tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 15 fw flowid 1:15
tc filter add dev $DEV parent 1:0 prio 0 protocol ip handle 16 fw flowid 1:16

iptables -t mangle -N MYSHAPER-OUT
iptables -t mangle -I POSTROUTING -o $DEV -j MYSHAPER-OUT

for PORT in $PRIO_15; do
  iptables -t mangle -A MYSHAPER-OUT -p tcp --dport $PORT -j MARK --set-mark 15
done

for PORT in $PRIO_13; do
  iptables -t mangle -A MYSHAPER-OUT -p tcp --dport $PORT -j MARK --set-mark 13
done


for PORT in $PRIO_12; do
  iptables -t mangle -A MYSHAPER-OUT -p tcp --dport $PORT -j MARK --set-mark 12
done


for PORT in $PRIO_11; do
  iptables -t mangle -A MYSHAPER-OUT -p tcp --dport $PORT -j MARK --set-mark 11
done


for PORT in $PRIO_HIGH_10; do
  iptables -t mangle -A MYSHAPER-OUT -p tcp --dport $PORT -j MARK --set-mark 10
done


#
# static rules
# icmp
#
iptables -t mangle -A MYSHAPER-OUT -p icmp -j MARK --set-mark 10
# dns
iptables -t mangle -A MYSHAPER-OUT -p udp --dport 53 -j MARK --set-mark 11
iptables -t mangle -A MYSHAPER-OUT -p udp --sport 53 -j MARK --set-mark 11
iptables -t mangle -A MYSHAPER-OUT -p tcp --sport 22 -j MARK --set-mark 11
# mark tcp ack,syns and so on
iptables -t mangle -A MYSHAPER-OUT -p tcp -m length --length :64 -j MARK --set-mark 10
iptables -t mangle -A MYSHAPER-OUT -p tcp -m length --length :52 -j MARK --set-mark 10

# mark ipp2p with 16(lowest)
iptables -t mangle -A MYSHAPER-OUT -m ipp2p --ipp2p -j MARK --set-mark 16

# mark any other packets with mark 16
iptables -t mangle -A MYSHAPER-OUT -m mark --mark 0 -j MARK --set-mark 16
